export default function TermsPage() {
  return (
    <div style={{ background: '#f5f0e8', minHeight: '100vh', fontFamily: 'Georgia, serif', color: '#1a1410' }}>
      <div style={{ maxWidth: 680, margin: '0 auto', padding: '80px 24px' }}>
        <a href="/" style={{ fontSize: 12, color: '#8a7f6e', letterSpacing: '0.3em', textDecoration: 'none', textTransform: 'uppercase' }}>← Back</a>
        <h1 style={{ fontFamily: 'Georgia, serif', fontSize: 32, fontWeight: 300, margin: '32px 0 8px', letterSpacing: '0.06em' }}>Terms of Service</h1>
        <p style={{ fontSize: 12, color: '#8a7f6e', fontStyle: 'italic', marginBottom: 40 }}>Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
        {[
          ['Nature of Service', 'Wú · The Book of Changes provides I Ching divination readings for entertainment and reflective purposes only. Readings are generated by an AI system interpreting traditional hexagram symbolism. They do not constitute professional advice of any kind — financial, legal, medical, or otherwise.'],
          ['No Guarantees', 'We make no guarantee that any reading will be accurate, applicable, or useful to your situation. The I Ching is a tool for reflection, not prediction. All decisions remain entirely your own responsibility.'],
          ['Payment & Refunds', 'Each reading costs $3.99 USD, charged at time of purchase. Due to the immediate digital delivery of readings, all sales are final. If a technical error prevented you from receiving your reading, contact us for a resolution.'],
          ['Acceptable Use', 'You agree not to use this service if you are under 18 years of age. You agree not to attempt to circumvent payment or abuse the service in any way.'],
          ['Limitation of Liability', 'Wú shall not be liable for any decisions made based on readings, or for any direct, indirect, or consequential damages arising from use of this service.'],
          ['Changes to Terms', 'We may update these terms at any time. Continued use of the service constitutes acceptance of the updated terms.'],
        ].map(([title, body]) => (
          <div key={title as string} style={{ marginBottom: 32 }}>
            <h2 style={{ fontSize: 14, letterSpacing: '0.3em', fontWeight: 400, textTransform: 'uppercase', color: '#8a7f6e', marginBottom: 10 }}>{title}</h2>
            <p style={{ fontSize: 15, lineHeight: 1.85, fontWeight: 300, color: '#3d3528' }}>{body}</p>
          </div>
        ))}
      </div>
    </div>
  )
}
